title: CyRIC's Blog >
author: mariobob
email: realsanjay3293@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Just a blog where I post about random stuff
show_excerpts: false # set to true to show excerpts on the homepage
url: https://remixbot.tk
paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: cyrics-blog

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/bitbrain_
      icon: twitter-square
      color: cyan
    - url: https://bitbrain.itch.io
      icon: itch-io
      color: red
    - url: https://github.com/mariobob
      icon: github-square
      color: purple

# Build settings
theme: jekyll-dash

jekyll_analytics:
  GoogleAnalytics:
    id: UA-138959468-2
    anonymizeIp: false  

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
 - jekyll-analytics
